/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t wait_millisecond = 1000;
uint32_t wait_counter = 0;

//Define Registers

#define AHB2ENR *((volatile uint32_t*) 0x4002104C)
#define GPIOMODERB *((volatile uint32_t*) 0x42020400)
#define GPIOMODERC *((volatile uint32_t*) 0x42020800)
#define GPIODRB *((volatile uint32_t*) 0x42020414)
#define GPIODRC *((volatile uint32_t*) 0x42020814)
#define GPIOIDRC *((volatile uint32_t*) 0x42020810)


int main(void) {
	//Enable Clock for GPIO
	AHB2ENR |= 3 << 1;

	//Configure Pin as General purpose output mode
	GPIOMODERB ^= (1 << (15));
	GPIOMODERC ^= (1 << (15));
	GPIOMODERC ^= (3 << (26));

	while(1) {


		//Turn On LED
		if(GPIOIDRC & (1 << 13)){
			GPIODRB &= ~(1 << 7);
			GPIODRC |= (1 << 7);

		}else{
			GPIODRC &= ~(1 << 7);
			GPIODRB |= (1 << 7);
		}

		//Turn Off LED

	}
}
