/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint32_t wait_millisecond = 1000;
uint32_t wait_counter = 0;

//Define Registers

#define AHB2ENR *((volatile uint32_t*) 0x4002104C)
#define GPIOMODER *((volatile uint32_t*) 0x42020000)
#define GPIODR *((volatile uint32_t*) 0x42020014)

int main(void) {
	//Enable Clock for GPIO
	AHB2ENR |= 0x01 << 0;

	//Configure Pin as General purpose output mode
	GPIOMODER ^= (0x01 << (19));

	while(1) {
		int index;


		//Turn On LED
		GPIODR |= (0x01 << 9);

		for(index=0;index<wait_millisecond*333;index++);
		wait_counter = wait_counter + 1;

		//Turn Off LED
		GPIODR &= 0x00 << 0;

		for(index=0;index<wait_millisecond*333;index++);
		wait_counter = wait_counter + 1;
	}
}
